apiVersion: v1
kind: Config
current-context: my-kube-admin@my-kube-playground

clusters:
- name: my-kube-playground
  cluster:
    certificate-authority: /etc/kubernetes/pki/ca.cert
    # certificate-authority-data: ...   alternative to path to certificate (line above) is pass encrypted certificate data (e.g. cat ca.crt | base64)
    server: https://my-kube-playground:6443
# more clusters

contexts:
- name: my-kube-admin@my-kube-playground
  context:
    cluster: my-kube-playground
    user: my-kube-admin
    namespace: finance # can specify a specific namespace
# more contexts

users:
- name: my-kube-admin
  user:
    client-certificate: /etc/kubernetes/pki/users/admin.cert  # or client-certificate-data
    client-key: /etc/kubernetes/pki/users/admin.key # or client-key-data
# more users