apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper-pod
spec:
  containers:
    - name: ubuntu-sleeper
      image: ubuntu-sleeper
      command: ["sleep2.0"]   # overrides the Entrypoint instruction in the Dockerfile
      args: ["10"]            # overrides the CMD instruction in the Dockerfile