# namespace-level, applicable for all pods in it
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-resource-constraint
spec:
  limits:
    - default:          # default limit
        memory: 1Gi
      defaultRequest:   # default request
        memory: 1Gi
      max:              # limit - max limit set to container
        memory: 1Gi
      min:              # request - min request in a pod a container can make
        memory: 500Mi
      type: Container