# namespace-level, applicable for all pods in it
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-resource-constraint
spec:
  limits:
    - default:          # default limit
        cpu: 500m
      defaultRequest:   # default request
        cpu: 500m
      max:              # limit - max limit set to container
        cpu: "1"
      min:              # request - min request in a pod a container can make
        cpu: 100m
      type: Container